[project]
name = "blend"
version = "0.1.0"
description = "Fork of \"The repository for Blend, a holistic data discovery system\""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "duckdb>=1.4.3",
  "pandas>=2.3.3",
  "polars>=1.36.1",
  "tqdm>=4.67.1",
]
